#!name=RoPhim App Modifier
#!desc=Plugin để xử lý các yêu cầu api của ứng dụng RoPhim (RoTeam)
#!author=dabeecao & hscavn & chatgpt
#!url=https://raw.githubusercontent.com/sontran87/shadowrocket/refs/heads/master/module/rophim.module
[Script]
http-response ^https?:\/\/api\.rofilm\.net\/api\/app\/v1\/(?:auth\/(?:register|login)|user\/info)$ script-path=https://raw.githubusercontent.com/sontran87/shadowrocket/refs/heads/master/scripts/rophim.js, requires-body=true, max-size=-1

[MITM]
hostname = api.rofilm.net